### ISSUE TITLE
Unable to see eta_ota_app.exe

### ISSUE THREAD

**Issue by imnitin13** [Embetronicx/STM32-Bootloader#2]
Unable to see eta_ota_app.exe. please upload the same file

**Comment by Embetronicx** [comment]
We have not added that eta_ota_app.exe as this file will vary on each machine. You have to build it yourself on your machine by using the below command.

`gcc etx_ota_update_main.c RS232\rs232.c -IRS232 -Wall -Wextra -o2 -o etx_ota_app`

**Comment by imnitin13** [comment]
![Screenshot (33)](https://user-images.githubusercontent.com/65548606/175221342-0012b59d-428f-49dd-abe4-33d8c9ec008d.png)
I am getting this.
Do help i am working with STM32F207ZG.
