### ISSUE TITLE
ETX_Bootloader_2.0 Problem

### ISSUE THREAD

**Issue by timurlen44** [Embetronicx/STM32-Bootloader#5]
Hi i saw a problem in "etx_ota_update.c" file at line 369

ret = HAL_FLASH_Program( FLASH_TYPEPROGRAM_BYTE,
                               (ETX_APP_FLASH_ADDR + ota_fw_received_size),
                               data[4+i]
                             );

The error is the "data[4+i]" part. It should be replaced with "data[i]"

**Comment by Embetronicx** [comment]
Fixed it.
